name: internlink
description: A Flutter app connecting students with internship opportunities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_app_check: ^0.4.0
  google_sign_in: ^7.1.1

  # UI & Navigation
  go_router: ^16.2.1
  google_fonts: ^6.1.0

  # File Operations
  file_picker: ^10.3.2
  image_picker: ^1.0.4

  # Utilities
  shimmer: ^3.0.0
  url_launcher: ^6.2.2

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  file_picker:
    path: third_party/file_picker

flutter:
  uses-material-design: true
  assets:
    - assets/images/
