// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4J2QSDpzx4SIknHkZRNSdGYt9_BdckR4',
    appId: '1:255468736418:web:0377de5a9993231ae22cfb',
    messagingSenderId: '255468736418',
    projectId: 'intern-link-a1e1c',
    authDomain: 'intern-link-a1e1c.firebaseapp.com',
    storageBucket: 'intern-link-a1e1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVH6ViCPJ37ZfxJDCM5VGSfZFYbo4FGI',
    appId: '1:255468736418:android:7f99a16fd5a20c46e22cfb',
    messagingSenderId: '255468736418',
    projectId: 'intern-link-a1e1c',
    storageBucket: 'intern-link-a1e1c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4J2QSDpzx4SIknHkZRNSdGYt9_BdckR4',
    appId: '1:255468736418:web:bf9a9a482677ce06e22cfb',
    messagingSenderId: '255468736418',
    projectId: 'intern-link-a1e1c',
    authDomain: 'intern-link-a1e1c.firebaseapp.com',
    storageBucket: 'intern-link-a1e1c.firebasestorage.app',
  );
}
